module.exports={
    devServer:{
        proxy:{
            '/api':{
                target:'https://jsonplaceholder.typicode.com/comments',
                changeOrigin:true,
                pathRewrite:{
                    '^/api':''
                }
            }
        }
    }
}